name: nilean
description: "Everything in your mother tongue"
publish_to: 'none'

version: 1.1.0+10

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_core: ^4.2.0
  google_sign_in: ^7.2.0
  flutter_bloc: ^9.1.1
  google_fonts: ^6.3.2
  flutter_animate: ^4.5.2
  iconsax: ^0.0.8
  iconsax_plus: ^1.0.0
  hexcolor: ^3.0.1
  loading_animation_widget: ^1.3.0
  cloud_firestore: ^6.0.3
  equatable: ^2.0.7
  jiffy: ^6.4.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_charset_detector: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  uuid: ^4.5.1
  flutter_markdown: ^0.7.7+1
  dio: ^5.9.0
  flutter_gemini: ^3.0.0
  card_loading: ^0.3.2
  get: ^4.7.2
  share_plus: ^12.0.0
  clipboard: ^2.0.2
  url_launcher: ^6.3.2
  firebase_messaging: ^16.0.3
  flutter_local_notifications: ^19.4.2
  rate_us_on_store: ^0.0.4
  image_picker: ^1.2.0
  firebase_storage: ^13.0.3
  loader_overlay: ^5.0.0
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  cached_network_image: ^3.4.1
  firebase_app_check: ^0.4.1+1
  in_app_update: ^4.2.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: GizaStencil
      fonts:
        - asset: assets/fonts/gizastencil/GizaStencil.otf
        - asset: assets/fonts/gizastencil/Giza.otf
